
---- 260312 얼굴인식 로그인 프로젝트  ----- 
-- VECTOR 타입 사용하려면 EXTENSION  설치 필요 
CREATE EXTENSION IF NOT EXISTS vector; -- vector가 존재하지 않으면 EXTENSION  설치

create table test (
	test_id varchar
);

-- users 테이블 --
create table users (
	user_id int generated by default as identity primary key, -- 식별자를 기본으로 생성 , 인데스
	user_id_str varchar(255) not null unique, -- 실제 유저가 입력한 문자열 아이디 
	email varchar(255) not null, -- 이메일
	username varchar(100) not null,-- 사용자명
	gender VARCHAR(6) not null check ( gender in ('male','female' ) ), -- 성별
	agree_state BOOLEAN not null default false, -- 가입 동의여부, 
	created_at timestamp default current_timestamp,  -- 생성일
	updated_at timestamp default current_timestamp,  -- 갱신일
	description varchar(255)
);

-- check 제약조건은 특정조건 값만 저장되도록 강제 
-- 식별자 기본으로 생성 int generated by default identity

-- face 테이블 -- 
create TABLE faceText (
	face_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 얼굴 인덱스
	user_id  int not null UNIQUE, -- 부모에서 참조 ,중복 방지 ( 1:1 관계)
	face_encoding TEXT not null, -- 벡터(실수배열파일)을 문자열로 변환 저장(JSON, CVS) 
	-- image_path varchar(255) not null, -- 저장된 파일경로 (상대경로 저장)
	created_at timestamp default current_timestamp, --생성일
	updated_at timestamp default current_timestamp, -- 갱신일
	description varchar(255),
	
	constraint fk_user_id foreign key (user_id) 
	references users(user_id) ON DELETE CASCADE
);

-- vector 타입 생성 전 extension 켜기 
CREATE EXTENSION  vector;

--현재 도커 연결 데이터베이스
SELECT current_database();
--  pgvector 생성하기
SELECT version();
CREATE EXTENSION vector;
--- extension 설치 되어있으면 extension 조회됨
SELECT * 
FROM pg_available_extensions 
WHERE name='vector';

-- 도커와 디비 연결잘 됬는지 확인
SELECT version(), inet_server_port();


create TABLE faceVector (
	face_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 얼굴 인덱스
	user_id  int not null UNIQUE, -- 부모에서 참조 ,중복 방지 ( 1:1 관계)
	face_encoding VECTOR(128) not null, -- pgvector사용하여 벡터값을 직접 저장?
	-- image_path varchar(255) not null, -- 저장된 파일경로 (상대경로 저장)
	created_at timestamp default current_timestamp, --생성일
	updated_at timestamp default current_timestamp, -- 갱신일
	description varchar(255),
	
	constraint fk_user_id foreign key (user_id) 
	references users(user_id) ON DELETE CASCADE
);




-- pk는 자동으로 인덱스르 생성하여 인덱스로 사용됨

-- 부모컬럼 user_id 삭제되면 같이 삭제
-- 사용자 ID를 먼저 찾고 얼굴 비교 ( 방법 1)
-- pgvector (PostgreSQL), AI 벡터 검색 디비 사용 ( 방법 2) 
-- pgvector  : pgvector는 여러 거리 계산을 지원 -- 디비 서버에 extension 이 설치되어있어양함
-- (Euclidean distance[<->] /inner product [<#>] / cosine distance [<=>]  )
-- 얼굴 특징을 벡터로 변환하여 PostgreSQL의 pgvector 확장을 사용해 유사도 검색을 수행하도록 설계




---- 260317데이터베이스 작업 -: 기본사용자 미등록 방지를 위한 state 컬럼 추가
--- check 를 사용해야 마이그레이션과 상태관리가 편리함
alter table users add column status varchar(20) 
check (status IN ('PENDING_FACE','ACTIVE'))
DEFAULT 'PENDING_FACE';

--- 260325 사용자 테이블 가데이터 추가
INSERT INTO users (
    user_id_str,
    email,
    -- username,
    -- gender,
    agree_state,
    description,
    status
) VALUES (
    'user_001',
    'testuser@example.com',
    -- 'testuser',
    -- 'male',
    true,
    '테스트 사용자입니다.',
    'PENDING_FACE'
);

select user_id_str from users;
update  users 
	set user_id_str = 'user01'
where user_id_str ='user_001';

------- 260327 ------
select * from users;

---- 260331 벡터 타입 변경하기 faceNet 에 맞춰서 512로--

alter table facevector
alter column face_encoding TYPE vector(512);

-- 만약 데이터가 있다면  USING face_vector::vector(512); 사용 ( :: 기호는 형변환 기호 )
ALTER TABLE users 
ALTER COLUMN face_vector TYPE vector(512) 
USING face_vector::vector(512);

--- 260401 user테이블 제약조건 확인 : 자식테이블에서 부모의 속성을 FK로참조하고있으니까 
SELECT conname FROM pg_constraint WHERE conrelid = 'facevector'::regclass;

--- 260401  users usrId 타입 bigint로 변경 트랜잭션 --

BEGIN;
	-- 자식테이블 FK 먼저 해제
	ALTER TABLE facevector DROP CONSTRAINT IF EXISTS fk_user_id;

	-- 부모테이블 int 에서 bigint로 변경 (자바타입이 Long)
	alter table users alter column user_id TYPE bigint;
	-- 자식테이블도 동일하게 변경
	alter table facevector alter column user_id TYPE bigint;

	-- 외래키 제약조건 재생성
	ALTER TABLE facevector 
	ADD CONSTRAINT fk_user_id 
	FOREIGN KEY (user_id) REFERENCES users (user_id) 
	ON DELETE CASCADE;


--실패하면 
rollback;
-- 완성되면 
commit;
	
	

