#서버 실행 포트
server:
  port: 8081 #서버포트 설정
  servlet: #컨텍스트 패스 설정
    context-path: / #JSP의 pageContext.request.contextpath

#애플리케이션명
spring:
  application:
    name: face-login
  #JSP를 뷰로 사용하면 View Reslover가 작동하므로 설정 및 폴더생성 필요
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  #SMTP 설정
  mail:
    host: smtp.gmail.com          # 구글 SMTP 서버 주소
    port: 587                     # TLS 포트 번호
    username: kbo8311@gmail.com    # 본인의 구글 이메일
    password:  czbq bqaz gptx lihc # 방금 발급받은 16자리 앱 비밀번호 (공백 제외)
    properties:
      mail:
        smtp:
          auth: true              # 사용자 인증 사용 여부
          starttls:
            enable: true          # 보안 연결(TLS) 활성화
          connectiontimeout: 5000 # 연결 시간 초과 (5초)
          timeout: 5000
          writetimeout: 5000
#데이터베이스 설정
  datasource:
    url: jdbc:postgresql://localhost:5433/facedb
    username: facedb
    password: java
    driver-class-name: org.postgresql.Driver
  flyway: #기존 디비를 기준으로 초기화 등록
    baseline-on-migrate: true
  docker: # 도커 미사용 시 , false 변경
    compose:
      enabled: true


logging:
  level:
    root: info
    org.springframework: info
    org.springframework.jdbc: info
    org.springframework.security: DEBUG
    org.mybatis: debug



#컨텍스트 패스 설정

#클래스 패스란? 
#프로그램 실행 시 JVM이 클래스와 리소스를 찾는 기준 경로
#자바 프로그램이 파일을 찾는 기준 위치