-- VECTOR 타입 사용하려면 EXTENSION  설치 필요 ( 가장먼저 실행)
CREATE EXTENSION IF NOT EXISTS vector; -- vector가 존재하지 않으면 EXTENSION  설치


-- 2. users 테이블 (부모)
CREATE TABLE IF NOT EXISTS users (
     user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 자바 Long 타입 대응
     user_id_str VARCHAR(255) NOT NULL UNIQUE,                    -- 로그인용 ID
     email VARCHAR(255) NOT NULL,                                 -- 이메일
     agree_state BOOLEAN NOT NULL DEFAULT FALSE,                  -- 가입 동의여부
     status VARCHAR(20) DEFAULT 'ACTIVE'                          -- 가입 상태 (check 제약조건은 우선 단일조건으로 )
         CHECK (status = 'ACTIVE'),
     user_role VARCHAR(20) NOT NULL DEFAULT 'USER',               -- 권한 (USER, ADMIN 등)
     description VARCHAR(255),                                    -- 설명
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,              -- 생성일
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP               -- 수정일
);


-- 3. facevector 테이블 (자식: 1:1 관계)
CREATE TABLE IF NOT EXISTS facevector (
  face_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE,                              -- 1:1 관계를 위한 UNIQUE
  face_encoding VECTOR(512) NOT NULL,                          -- FaceNet 512차원 벡터
  description VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

-- 외래키 설정: 부모 삭제 시 함께 삭제 (ON DELETE CASCADE)
  CONSTRAINT fk_user_id FOREIGN KEY (user_id)
      REFERENCES users(user_id) ON DELETE CASCADE
);

-- 4. 인덱스 생성 (성능 최적화)
-- 코사인 유사도 검색을 주로 사용하신다면 벡터 인덱스 추가를 고려할 수 있습니다.
-- CREATE INDEX ON facevector USING hnsw (face_encoding vector_cosine_ops);
